/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ApiPublicProxyRouteImport } from './routes/api/public/proxy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyRoute = ApiPublicProxyRouteImport.update({
  id: '/api/public/proxy',
  path: '/api/public/proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$id': typeof SIdRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$id': typeof SIdRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$id': typeof SIdRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$id' | '/api/public/proxy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$id' | '/api/public/proxy'
  id: '__root__' | '/' | '/s/$id' | '/api/public/proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SIdRoute: typeof SIdRoute
  ApiPublicProxyRoute: typeof ApiPublicProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy': {
      id: '/api/public/proxy'
      path: '/api/public/proxy'
      fullPath: '/api/public/proxy'
      preLoaderRoute: typeof ApiPublicProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SIdRoute: SIdRoute,
  ApiPublicProxyRoute: ApiPublicProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
